#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  GITFLOW_COMMAND="git flow"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  GITFLOW_COMMAND="git-flow"
fi

echo "It is assumed that you have merged your changes into develop branch."
echo "Creating a release branch release/$RELEASE_VERSION from develop branch"
git checkout develop

echo "Write release notes in CHANGELOG.txt"
$editor CHANGELOG.txt

RELEASE_VERSION=$(head -n1 CHANGELOG.txt | awk '{ print $1 }')
${GITFLOW_COMMAND} release start ${RELEASE_VERSION}

git diff
echo "Verify changes before commit."
git commit -a -m "Bump ${RELEASE_VERSION}" --signoff --no-verify


echo "Push branch to git remote"
${GITFLOW_COMMAND} release publish ${RELEASE_VERSION}
